language: java
jdk:
  - openjdk8
sudo: false
cache:
  - directories:
      - $HOME/.m2
env:
  - MAVEN_OPTS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1
notifications:
  email:
    on_failure: always
    on_success: never
install:
  - "mvn clean install -T 1C -DdependencyLocationsEnabled=false"
deploy:
  provider: releases
  file:
    - "WorldBorderAPITestPlugin/target/WorldBorderAPITestPlugin*.jar"
    - "API/target/API*.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: yannicklamprecht/WorldBorderAPI
  overwrite: true
  api_key:
    secure: 
