  on:
    push:
      branches:
        - master
        - develop
  jobs:
    build:
      strategy:
        matrix:
          java-version: [ '11' ]
          os: [ 'ubuntu-latest']
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout Source Code
          uses: actions/checkout@v1
        - name: Setup Java ${{ matrix.java-version }}
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java-version }}
            architecture: x64
        - name: Download BuildTools
          run: ./gradlew downloadBuildTools
        - name: Build Spigot
          run: "./gradlew buildSpigot"
        - name: Build with gradle
          run: ./gradlew build shadowJar
        - uses: "actions/upload-artifact@v2-preview"
          with:
            name: "WorldBorderPlugin"
            path: "WorldBorderPlugin/build/libs/WorldBorderPlugin-*-all.jar"
        - uses: "actions/upload-artifact@v2-preview"
          with:
            name: "API"
            path: "API/build/libs/API-*.jar"
        - uses: "actions/upload-artifact@v2-preview"
          with:
            name: "WorldBorderAPITestPlugin"
            path: "WorldBorderAPITestPlugin/build/libs/WorldBorderAPITestPlugin-*-all.jar"
