  on:
    push:
      branches:
        - master
        - develop
  jobs:
    build:
      strategy:
        matrix:
          java-version: [ '11' ]
          os: [ 'ubuntu-latest']
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout Source Code
          uses: actions/checkout@v1
        - name: Setup Java ${{ matrix.java-version }}
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java-version }}
            architecture: x64
        - name: Download BuildTools
          run: ./gradlew downloadBuildTools
        - name: Build Spigot 1.14
          run: "./gradlew 1_14_R1:buildSpigot"
        - name: Build Spigot 1.15
          run: "./gradlew 1_15_R1:buildSpigot"
        - name: Build Spigot 1.16
          run: "./gradlew 1_16_R3:buildSpigot"
        - name: Build with gradle
          run: ./gradlew build shadowJar
