  on:
    push:
      branches:
        - master
        - develop
  jobs:
    build:
      strategy:
        matrix:
          java-version: [ '16' ]
          os: [ 'ubuntu-latest']
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout Source Code
          uses: actions/checkout@v1
        - name: Setup Java ${{ matrix.java-version }}
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java-version }}
            architecture: x64
        - name: Build with gradle
          run: ./gradlew cleanup setup clean shadowJar
          # todo remap when special source is fixed or another tool is implemented
        # - uses: "actions/upload-artifact@v2" todo use again when special source is fixed or another tool is implemented
        #   with:
        #     name: "plugin-mojang"
        #     path: "plugin/build/libs/plugin-*-mojang.jar"
        - uses: "actions/upload-artifact@v2"
          with:
            name: "plugin-spigot"
            path: "plugin/build/libs/plugin-*-spigot.jar"
        - uses: "actions/upload-artifact@v2"
          with:
            name: "api"
            path: "api/build/libs/api-*.jar"
        - uses: "actions/upload-artifact@v2"
          with:
            name: "testplugin"
            path: "testplugin/build/libs/testplugin-*.jar"
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              plugin/build/libs/plugin-*-spigot.jar
              plugin/build/libs/plugin-*-mojang.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

